// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restoran.DAL;

#nullable disable

namespace Restoran.DAL.Migrations
{
    [DbContext(typeof(RestoranContext))]
    [Migration("20251227140443_DodajNarudzbinuFK")]
    partial class DodajNarudzbinuFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restoran.DAL.Entities.Gost", b =>
                {
                    b.Property<int>("IDGosta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDGosta"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImeGosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrezimeGosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDGosta");

                    b.ToTable("Gost", (string)null);
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Ime")
                        .IsUnique();

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktivan = true,
                            Ime = "menadzer",
                            Lozinka = "1234",
                            Uloga = 0
                        },
                        new
                        {
                            Id = 2,
                            Aktivan = true,
                            Ime = "kuvar",
                            Lozinka = "1234",
                            Uloga = 1
                        },
                        new
                        {
                            Id = 3,
                            Aktivan = true,
                            Ime = "konobar",
                            Lozinka = "1234",
                            Uloga = 2
                        });
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Narudzbina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojStola")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Proizvod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RezervacijaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Narudzbine");
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Rezervacija", b =>
                {
                    b.Property<int>("IDRezervacije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRezervacije"));

                    b.Property<int>("BrojOsoba")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDGosta")
                        .HasColumnType("int");

                    b.Property<int>("IDStola")
                        .HasColumnType("int");

                    b.Property<int?>("NarudzbinaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Vreme")
                        .HasColumnType("time");

                    b.HasKey("IDRezervacije");

                    b.HasIndex("IDGosta");

                    b.HasIndex("IDStola");

                    b.HasIndex("NarudzbinaId")
                        .IsUnique()
                        .HasFilter("[NarudzbinaId] IS NOT NULL");

                    b.ToTable("Rezervacija", (string)null);
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Sto", b =>
                {
                    b.Property<int>("IDStola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDStola"));

                    b.Property<int>("BrojMesta")
                        .HasColumnType("int");

                    b.Property<int>("BrojStola")
                        .HasColumnType("int");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDStola");

                    b.ToTable("Sto", (string)null);
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Rezervacija", b =>
                {
                    b.HasOne("Restoran.DAL.Entities.Gost", "Gost")
                        .WithMany("Rezervacije")
                        .HasForeignKey("IDGosta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restoran.DAL.Entities.Sto", "Sto")
                        .WithMany("Rezervacije")
                        .HasForeignKey("IDStola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restoran.DAL.Entities.Narudzbina", "Narudzbina")
                        .WithOne("Rezervacija")
                        .HasForeignKey("Restoran.DAL.Entities.Rezervacija", "NarudzbinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gost");

                    b.Navigation("Narudzbina");

                    b.Navigation("Sto");
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Gost", b =>
                {
                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Narudzbina", b =>
                {
                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("Restoran.DAL.Entities.Sto", b =>
                {
                    b.Navigation("Rezervacije");
                });
#pragma warning restore 612, 618
        }
    }
}
